FROM node:22-bookworm-slim

WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
ENV PORT=4173
ENV BASE_PATH=/

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json tsconfig.json replit.md ./
COPY artifacts ./artifacts
COPY lib ./lib
#COPY scripts ./scripts
COPY attached_assets ./attached_assets

RUN pnpm install --frozen-lockfile

WORKDIR /app/artifacts/sentinelx

EXPOSE 4173

CMD ["pnpm", "run", "dev"]