import { useEffect } from "react";
import { Link } from "wouter";
import { Navbar } from "@/components/layout/Navbar";
import { StatCounter } from "@/components/ui/StatCounter";
import { ThreatFeed } from "@/components/ui/ThreatFeed";
import { Button } from "@/components/ui/button";
import { Shield, Search, QrCode, Activity, Eye, Globe, Cpu, ChevronRight, Linkedin } from "lucide-react";
import { SiGithub, SiX } from "react-icons/si";

export default function Landing() {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none" />
      <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] rounded-full bg-primary/10 blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] rounded-full bg-secondary/10 blur-[120px] pointer-events-none" />

      <Navbar />

      <main className="relative z-10">
        <section className="container mx-auto px-4 pt-32 pb-24 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary text-sm font-mono mb-8 animate-pulse shadow-[0_0_10px_rgba(0,245,255,0.2)]">
            <Activity className="w-4 h-4" />
            <span>SYSTEM ONLINE • THREAT INTELLIGENCE ACTIVE</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-bold font-display tracking-tight text-white mb-6">
            AI-Powered <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">Cyber Threat</span><br />Defense Platform
          </h1>
          
          <p className="mt-4 text-xl text-muted-foreground max-w-3xl mx-auto mb-10 leading-relaxed">
            Enterprise-grade phishing detection, real-time sandbox analysis, and predictive threat intelligence. Secure your infrastructure before the breach happens.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button asChild size="lg" className="h-14 px-8 text-lg font-bold bg-primary text-primary-foreground hover:bg-primary/90 shadow-[0_0_20px_rgba(0,245,255,0.4)]">
              <Link href="/sandbox">
                <Search className="mr-2 h-5 w-5" /> Analyze URL Now
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="h-14 px-8 text-lg font-bold border-white/20 hover:bg-white/5 backdrop-blur-sm">
              <Link href="/dashboard">
                <Eye className="mr-2 h-5 w-5" /> View Live Threats
              </Link>
            </Button>
          </div>
        </section>

        <section className="container mx-auto px-4 py-20">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <StatCounter end={2451000} label="Threats Blocked" suffix="+" prefix=">" />
            <StatCounter end={18700000} label="URLs Analyzed" suffix="+" />
            <StatCounter end={847000} label="QR Scams Prevented" suffix="+" />
            <StatCounter end={156000} label="Malware Samples" suffix="+" />
          </div>
        </section>

        <section className="container mx-auto px-4 py-20">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { title: "URL Sandbox Analysis", icon: Search, desc: "Safely detonate and inspect suspicious links in isolated environments." },
                { title: "QR Scam Detection", icon: QrCode, desc: "Extract and verify QR code destinations before mobile scanning." },
                { title: "Malware Behavior Tracking", icon: Activity, desc: "Monitor script execution and anomalous payload behavior." },
                { title: "Threat Intelligence", icon: Globe, desc: "Global repository of known malicious domains and IPs." },
                { title: "AI Risk Explanation", icon: Cpu, desc: "Human-readable summaries of complex threat vectors generated by AI." },
                { title: "Browser Protection", icon: Shield, desc: "Prevent credential harvesting and session hijacking." },
              ].map((feat, i) => (
                <div key={i} className="group p-6 rounded-2xl bg-card/40 border border-white/5 hover:border-primary/50 transition-all duration-300 backdrop-blur-sm hover:shadow-[0_0_20px_rgba(0,245,255,0.15)] relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-primary to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                  <feat.icon className="w-10 h-10 text-muted-foreground group-hover:text-primary transition-colors mb-4 drop-shadow-[0_0_10px_rgba(0,245,255,0)] group-hover:drop-shadow-[0_0_10px_rgba(0,245,255,0.8)]" />
                  <h3 className="text-xl font-bold font-display text-white mb-2">{feat.title}</h3>
                  <p className="text-muted-foreground text-sm">{feat.desc}</p>
                </div>
              ))}
            </div>
            <div className="lg:col-span-1 h-[600px]">
              <ThreatFeed />
            </div>
          </div>
        </section>


      </main>

      <footer className="border-t border-border bg-card/80 backdrop-blur-sm py-12 relative z-10">
        <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="md:col-span-2">
            <Link href="/" className="flex items-center gap-2 mb-4">
              <Shield className="h-6 w-6 text-primary" />
              <span className="text-lg font-bold font-display">SentinelX</span>
            </Link>
            <p className="text-muted-foreground text-sm max-w-sm mb-6">
              Advanced cyber threat intelligence and sandbox analysis platform. Next-generation security for modern infrastructure.
            </p>
            <div className="flex gap-4">
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-white"><SiGithub className="w-5 h-5" /></Button>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-white"><SiX className="w-5 h-5" /></Button>
              <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-white"><Linkedin className="w-5 h-5" /></Button>
            </div>
          </div>
          <div>
            <h4 className="font-bold text-white mb-4">Platform</h4>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li><Link href="/sandbox" className="hover:text-primary">Sandbox Analyzer</Link></li>
              <li><Link href="/qr" className="hover:text-primary">QR Detection</Link></li>
              <li><Link href="/dashboard" className="hover:text-primary">Live Dashboard</Link></li>
              <li><Link href="/intelligence" className="hover:text-primary">Threat Intel</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-white mb-4">Company</h4>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li><Link href="/about" className="hover:text-primary">About Us</Link></li>
              <li><Link href="/community" className="hover:text-primary">Community</Link></li>
              <li><Link href="/contact" className="hover:text-primary">Contact</Link></li>
              <li><Link href="/admin" className="hover:text-primary">Admin</Link></li>
            </ul>
          </div>
        </div>
        <div className="container mx-auto px-4 mt-12 pt-8 border-t border-border text-center text-sm text-muted-foreground">
          &copy; {new Date().getFullYear()} SentinelX Security Systems. All rights reserved.
        </div>
      </footer>
    </div>
  );
}